# Generated by Django 4.1.1 on 2022-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='master password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
