# Generated by Django 4.1.1 on 2022-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hint',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
