# Generated by Django 4.1.1 on 2022-09-19 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_hint_alter_user_password_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ManyToManyField(related_name='questions', to='authentication.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
