# Generated by Django 4.1.1 on 2022-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_folder_pirority'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='items',
            field=models.ManyToManyField(related_name='folder_items', to='vault.item'),
        ),
    ]
