# Generated by Django 4.1.1 on 2022-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_folder_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pirority',
            new_name='piority',
        ),
    ]
