# Generated by Django 4.1.1 on 2022-09-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_rename_pirority_item_piority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='pirority',
            new_name='piority',
        ),
    ]
